[package]
name = "rode-battle-judge"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { version = "1.11.0", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.144.0", features = ["behavior-version-latest"] }
axum = { version = "0.8.9", features = ["macros"] }
byte-unit = "5.2.0"
chrono = { version = "0.4.44", features = ["serde"] }
code-executor = "1.1.0"
color-eyre = "0.6.5"
config = { version = "0.15.22", default-features = false }
futures-lite = "2.6.1"
html-renderer = "1.0.0"
image = "0.25.10"
image-compare = "0.5.0"
lapin = "4.7.2"
moka = { version = "0.12.16", features = ["future"] }
o2o = { version = "0.5.5", features = ["o2o-impl"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "chrono", "uuid"] }
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "chrono", "env-filter"] }
utoipa = "5.5.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
uuid = { version = "1.23.1", features = ["v4", "fast-rng"] }
