services:
  judge:
    image: ${REGISTRY}/judge:latest
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache,mode=max
